// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"context"
	"github.com/comeonjy/go-kit/pkg/xlog"
	"spider/configs"
	"spider/internal/data"
	"spider/internal/scheduler"
	"spider/internal/server"
	"spider/internal/service"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, logger *xlog.Logger) *App {
	configsInterface := configs.NewConfig(ctx)
	dataData := data.NewData(configsInterface, logger)
	taskRepo := data.NewTaskRepo(dataData)
	spiderService := service.NewSpiderService(configsInterface, logger, taskRepo)
	grpcServer := server.NewGrpcServer(spiderService, configsInterface, logger)
	httpServer := server.NewHttpServer(ctx, configsInterface, logger)
	fetchRecordRepo := data.NewFetchRecordRepo(dataData)
	resourceRepo := data.NewResourceRepo(dataData)
	schedulerScheduler := scheduler.NewScheduler(configsInterface, logger, taskRepo, fetchRecordRepo, resourceRepo)
	app := newApp(ctx, grpcServer, httpServer, configsInterface, schedulerScheduler)
	return app
}
